### ISSUE TITLE
document SMH Rbac requirements

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo-mesh#1023]
currently we have no documented reference to the set of RBAC 

The current rbac config assigned to the remote service account by cluster registration looks as follows:
```yaml
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appmesh.k8s.aws
  resources:
  - meshes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - certificates.smh.solo.io
  resources:
  - issuedcertificates
  - podbouncedirectives
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - virtualservices
  - envoyfilters
  - serviceentries
  - gateways
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - authorizationpolicies
  verbs:
  - '*'
- apiGroups:
  - access.smi-spec.io
  resources:
  - traffictargets
  verbs:
  - '*'
- apiGroups:
  - specs.smi-spec.io
  resources:
  - httproutegroups
  verbs:
  - '*'
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits
  verbs:
  - '*'
- apiGroups:
  - certificates.smh.solo.io
  resources:
  - issuedcertificates
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.smh.solo.io
  resources:
  - issuedcertificates/status
  - certificaterequests/status
  verbs:
  - get
  - update


```

These RBAC Policy Rules can be seen by inspecting the `ClusterRole` created for SMH in the registered cluster namespace
