### ISSUE TITLE
Can't use several subsets in a trafficShift kubeService destination

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-mesh#1091]
**Describe the bug**
Here is the error it generates in the networking logs:

```
2020-11-23T14:40:54.332Z	ERROR	networking.reconcile-105	failed upserting resource	{"resource": "reviews.default.cluster1.*v1alpha3.VirtualService", "err": "admission webhook \"validation.istio.io\" denied the request: configuration is invalid: subset name is invalid: app-reviews_version-v3"}
github.com/solo-io/skv2/contrib/pkg/output.Snapshot.upsert
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/output/snapshot.go:321
github.com/solo-io/skv2/contrib/pkg/output.Snapshot.syncList
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/output/snapshot.go:263
github.com/solo-io/skv2/contrib/pkg/output.Snapshot.SyncMultiCluster
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/output/snapshot.go:250
github.com/solo-io/gloo-mesh/pkg/api/networking.mesh.gloo.solo.io/output/istio.(*snapshot).ApplyMultiCluster
	/workspace/gloo-mesh/pkg/api/networking.mesh.gloo.solo.io/output/istio/snapshot.go:312
github.com/solo-io/gloo-mesh/pkg/mesh-networking/translation.OutputSnapshots.Apply
	/workspace/gloo-mesh/pkg/mesh-networking/translation/networking_translator.go:59
github.com/solo-io/gloo-mesh/pkg/mesh-networking/reconciliation.(*networkingReconciler).applyTranslation
	/workspace/gloo-mesh/pkg/mesh-networking/reconciliation/networking_reconciler.go:174
github.com/solo-io/gloo-mesh/pkg/mesh-networking/reconciliation.(*networkingReconciler).reconcile
	/workspace/gloo-mesh/pkg/mesh-networking/reconciliation/networking_reconciler.go:148
github.com/solo-io/skv2/contrib/pkg/input.(*inputReconciler).processNextWorkItem
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/input/input_reconciler.go:138
github.com/solo-io/skv2/contrib/pkg/input.(*inputReconciler).reconcileEventsForever
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/input/input_reconciler.go:114
2020-11-23T14:40:54.341Z	ERROR	networking.reconcile-105	failed upserting resource	{"resource": "reviews-default-cluster1.istio-system.cluster2.*v1alpha3.VirtualService", "err": "admission webhook \"validation.istio.io\" denied the request: configuration is invalid: subset name is invalid: app-reviews_version-v3"}
github.com/solo-io/skv2/contrib/pkg/output.Snapshot.upsert
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/output/snapshot.go:321
github.com/solo-io/skv2/contrib/pkg/output.Snapshot.syncList
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/output/snapshot.go:263
github.com/solo-io/skv2/contrib/pkg/output.Snapshot.SyncMultiCluster
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/output/snapshot.go:250
github.com/solo-io/gloo-mesh/pkg/api/networking.mesh.gloo.solo.io/output/istio.(*snapshot).ApplyMultiCluster
	/workspace/gloo-mesh/pkg/api/networking.mesh.gloo.solo.io/output/istio/snapshot.go:312
github.com/solo-io/gloo-mesh/pkg/mesh-networking/translation.OutputSnapshots.Apply
	/workspace/gloo-mesh/pkg/mesh-networking/translation/networking_translator.go:59
github.com/solo-io/gloo-mesh/pkg/mesh-networking/reconciliation.(*networkingReconciler).applyTranslation
	/workspace/gloo-mesh/pkg/mesh-networking/reconciliation/networking_reconciler.go:174
github.com/solo-io/gloo-mesh/pkg/mesh-networking/reconciliation.(*networkingReconciler).reconcile
	/workspace/gloo-mesh/pkg/mesh-networking/reconciliation/networking_reconciler.go:148
github.com/solo-io/skv2/contrib/pkg/input.(*inputReconciler).processNextWorkItem
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/input/input_reconciler.go:138
github.com/solo-io/skv2/contrib/pkg/input.(*inputReconciler).reconcileEventsForever
	/go/pkg/mod/github.com/solo-io/skv2@v0.13.3/contrib/pkg/input/input_reconciler.go:114
```

**To Reproduce**
Here is an example of a `TrafficPolicy` to reproduce the issue:

```
apiVersion: networking.mesh.gloo.solo.io/v1alpha2
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: simple
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: cluster1
          name: reviews
          namespace: default
  trafficShift:
    destinations:
      - kubeService:
          clusterName: cluster2
          name: reviews
          namespace: default
          subset:
            version: v3
            app: reviews
        weight: 75
      - kubeService:
          clusterName: cluster1
          name: reviews
          namespace: default
          subset:
            version: v1
        weight: 15
      - kubeService:
          clusterName: cluster1
          name: reviews
          namespace: default
          subset:
            version: v2
        weight: 10
```

**Additional context**
- Gloo Mesh version 0.10.3
