### ISSUE TITLE
Federation fails when port doesn't resolve correctly

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1146]
A port such as:

```yaml
  - name: status-port
    number: 15021
    protocol: TCP
```

cannot be resolved to a valid AppProtocol via the function invoked [here](https://github.com/solo-io/gloo-mesh/blob/v0.10.9/pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go#L390). In the event that the response is UnsupportedProtocol, we should fallback to the protocol specified on the kube service port.
