### ISSUE TITLE
TrafficPolicy status is not updated to reflect deleted TrafficTargets

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh#1232]
**Describe the bug**
If a user deletes a service, Gloo Mesh discovery will delete the corresponding traffic target. However, TrafficPolicy (and perhaps AccessPolicy) status will not be updated by this event and will display the nonexistent traffic target in its list of traffic targets configured by the policy.

This is a correctness issue and can cause problems in tooling such as the Gloo Mesh dashboard.

**To Reproduce**
1. Install gloo mesh, istio, and bookinfo on a cluster
2. Register the cluster
3. Create a traffic policy that configures the Details service (or all services) and wait for it to sync
4. Delete the Details service.
5. Observe that the traffic policy's status still includes details in its list of traffic targets.

**Expected behavior**
I would expect the traffic policy status to not reference any nonexistent traffic targets or workloads. 

**Additional context**
- Gloo Mesh version 0.12.2
- Kubernetes version 1.19
- Istio 1.8

**Comment by joekelley** [comment]
Interestingly, this is not resolved by updating the traffic policy to update its resource version.

**Comment by ryantking** [comment]
Test traffic policy:
```
apiVersion: networking.mesh.gloo.solo.io/v1alpha2
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: details
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: mgmt-cluster
          name: details
          namespace: bookinfo
        - clusterName: mgmt-cluster
          name: reviews
          namespace: bookinfo
  requestTimeout: 100ms
  retries:
    attempts: 5
    perTryTimeout: 5ms
```
