### ISSUE TITLE
meshctl cluster register --cluster-domain default value isn't set correctly

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo-mesh#1356]
The help says the following:

```
--cluster-domain string     The Cluster Domain used by the Kubernetes DNS Service in the registered cluster. Defaults to 'cluster.local'.
```

But if `meshctl cluster register` is used without the `--cluster-domain` option, the cluster domain isn't set at all and a `KubernetesCluster` object is created as follow:

```
apiVersion: multicluster.solo.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: cluster2
  namespace: gloo-mesh
spec: {}
```

It should be created like that instead:

```
apiVersion: multicluster.solo.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: cluster2
  namespace: gloo-mesh
spec:
  clusterDomain: cluster.local
```
