### ISSUE TITLE
unknown field "trafficShift" in io.solo.gloo.mesh.networking.v1.TrafficPolicy.spec

### ISSUE THREAD

**Issue by rvennam** [solo-io/gloo-mesh#1402]
Applying the TrafficPolicy listed here: 
https://docs.solo.io/gloo-mesh/latest/guides/multicluster_communication/
```

apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: simple
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: mgmt-cluster
          name: reviews
          namespace: bookinfo
  trafficShift:
    destinations:
      - kubeService:
          clusterName: remote-cluster
          name: reviews
          namespace: bookinfo
        weight: 75
      - kubeService:
          clusterName: mgmt-cluster
          name: reviews
          namespace: bookinfo
          subset:
            version: v1
        weight: 15
      - kubeService:
          clusterName: mgmt-cluster
          name: reviews
          namespace: bookinfo
          subset:
            version: v2
        weight: 10
```

results in:
```
error: error validating "STDIN": error validating data: ValidationError(TrafficPolicy.spec): unknown field "trafficShift" in io.solo.gloo.mesh.networking.v1.TrafficPolicy.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

It's missing the `policy:`
