### ISSUE TITLE
Unable to use TrafficPolicy for cross cluster routing when service does not exist locally 

### ISSUE THREAD

**Issue by rvennam** [solo-io/gloo-mesh#1403]
Environment:
`kind-mgmt-cluster` with istio, gloo mesh and bookinfo
`kind-remote-cluster` with istio and bookinfo

Delete ratings from kind-mgmt-cluster
```
k delete deployment ratings-v1 -n bookinfo --context kind-mgmt-cluster
k delete service ratings -n bookinfo --context kind-mgmt-cluster
```
Apply traffic policy:
```
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: simple
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: mgmt-cluster # ratings doesn't exist in mgmt-cluster
          name: ratings
          namespace: bookinfo
  policy:
    trafficShift:
      destinations:
        - kubeService:
            clusterName: remote-cluster
            name: ratings
            namespace: bookinfo
          weight: 100
```

No VS is generated. I want a VS that looks like this:
```
  spec:
    hosts:
    - ratings.bookinfo.svc.cluster.local
    http:
    - route:
      - destination:
          host: ratings.bookinfo.svc.remote-cluster.global
        weight: 100
```

cc: @joekelley
