### ISSUE TITLE
TrafficPolicy for canary, by default route to original targeted destination

### ISSUE THREAD

**Issue by rvennam** [solo-io/gloo-mesh#1426]
How can I create a TrafficPolicy where if the httpRequestMatchers doesn't match, it defaults to normal routing behavior?
If it's not Firefox, I want it to continue to reviews in cluster1
```
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: multicluster-reviews-canary
spec:
  httpRequestMatchers:
    - headers:
        - name: user-agent
          value: '.*Firefox.*'
          regex: true
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: remotecluster1
          name: reviews
          namespace: default
  policy:
    trafficShift:
      destinations:
        - kubeService:
            clusterName: remotecluster3
            name: reviews
            namespace: default
            subset:
              version: v3
```

I want it to generate:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
...
  http:
    - match:
        - headers:
            user-agent:
              regex: '.*Firefox.*'
      route:
        - destination:
            host: reviews
            subset: v3
    - route:
        - destination:
            host: reviews
```

I also tried to apply a second TrafficPolicy to catch all:
```
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: multicluster-reviews-canary
spec:
  httpRequestMatchers:
    - headers:
        - name: user-agent
          value: '.*Firefox.*'
          regex: true
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: remotecluster1
          name: reviews
          namespace: default
  policy:
    trafficShift:
      destinations:
        - kubeService:
            clusterName: remotecluster3
            name: reviews
            namespace: default
            subset:
              version: v3
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: multicluster-reviews-canary-default
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: remotecluster1
          name: reviews
          namespace: default
  policy:
    trafficShift:
      destinations:
        - kubeService:
            clusterName: remotecluster1
            name: reviews
            namespace: default
            subset:
              version: v1
```

but that generated a VS http routes in the wrong order:
```
spec:
  hosts:
  - reviews.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: reviews.default.svc.cluster.local
        subset: version-v1
  - match:
    - headers:
        user-agent:
          regex: .*Firefox.*
    route:
    - destination:
        host: reviews.default.svc.remotecluster3.global
        subset: version-v3
```
cc @harveyxia
