### ISSUE TITLE
enterprise-agent segfaults when an invalid Destination is applied to a remote cluster

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo-mesh#1432]
**To Reproduce**
Start up Gloo Mesh enterprise with
```
meshctl demo istio-multicluster init --enterprise --license $GLOO_MESH_LICENSE_KEY
```

Apply the following resource:
```
apiVersion: discovery.mesh.gloo.solo.io/v1
kind: Destination
metadata:
  name: my-ext-service-dest
  namespace: gloo-mesh
spec:
  externalService:
    endpoints:
    - address: solo.io
      ports:
        http: 80
    hosts:
    - foo.bar.global
    name: my-external-service
    ports:
    - name: http
      number: 80
      protocol: HTTP
```

See that the enterprise-agent fails with the following error:
```
{"level":"fatal","ts":1618499681.5711305,"msg":"rpc error: code = Unknown desc = resource delete event handler failed: expected label owner.discovery.mesh.gloo.solo.io not on labels of Destination my-ext-service-dest.gloo-mesh.","stacktrace":"runtime.main\n\t/opt/hostedtoolcache/go/1.15.11/x64/src/runtime/proc.go:204"}
```

Then, this error causes the pod to go into a CrashLoopBackoff - until the bad Destination is deleted.

**Expected behavior**
Even if this Destination is invalid or not supported, it should not crash the enterprise-agent pod.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Mesh version - v1.0.4
- Kubernetes version - v1.17.5
- service mesh and version - Istio v1.9.1
