### ISSUE TITLE
Expose helm options for setting extra load balancer annotations

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo-mesh#1450]
**Is your feature request related to a problem? Please describe.**
A Gloo Mesh Enterprise customer who also uses Gloo Edge with Amazon EKS wants to be able to specify extra annotations in helm charts just as they can with [Edge](https://docs.solo.io/gloo-edge/latest/guides/integrations/aws/#how-to).  Specifically, they want to be able to specify AWS load balancer annotations like these:
```
service.beta.kubernetes.io/aws-load-balancer-type: nlb
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

**Describe the solution you'd like**
Use `extraAnnotations` support in Gloo Mesh similar to what exists in Edge today.

**Additional context**
Internal reference: https://solo-io.slack.com/archives/G01CB20BFR8/p1618495032029000

**Comment by ashleywang1** [comment]
This should now be possible in Gloo Mesh Enterprise v1.1.0-beta7, e.g.
```
enterpriseNetworking:
  service:
    extraAnnotations:
      - service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

**Comment by ashleywang1** [comment]
This has been released in Gloo Mesh oss v1.0.11

**Comment by harveyxia** [comment]
@ashleywang1 can you cut an enterprise release for this? thanks

**Comment by harveyxia** [comment]
@EItanya confirm that this is available in enterprise

**Comment by harveyxia** [comment]
@ashleywang1 

This change exists on `skv2@v0.17.19`, which needs to be brought into GM and GME, on both v1.0.x and v1.1.x branches

**Comment by ashleywang1** [comment]
GM v1.1.0-beta11 branch PR: https://github.com/solo-io/gloo-mesh/pull/1612

**Comment by ashleywang1** [comment]
A generalized way of doing this was done in skv2@v0.17.20. The following helm override file will allow you to override any operator-generated deployment or service for the gloo mesh components, e.g.
```
discovery:
  deploymentOverrides:
    spec:
      replicas: 5
      template:
        metadata:
          annotations:
            test: new-annotation
            app.kubernetes.io/name: test-replacing-annotation
```
