### ISSUE TITLE
Validate clusters in traffic policy from using '*'

### ISSUE THREAD

**Issue by nmnellis** [solo-io/gloo-mesh#1513]
**Describe the bug**
To include all clusters in a traffic policy destination you need to omit the clusters field rather than use '*'

Bad
```yaml
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: timeout-test
spec:
  destinationSelector:
  - kubeServiceMatcher:
      clusters: '*'
      labels:
        app: frontend
      namespaces:
      - {{.EchoContext.AppNamespace.Name}}
  policy:
    requestTimeout: 1s
```
Good
```yaml
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: timeout-test
spec:
  destinationSelector:
  - kubeServiceMatcher:
      labels:
        app: frontend
      namespaces:
      - {{.EchoContext.AppNamespace.Name}}
  policy:
    requestTimeout: 1s
```

**Expected behavior**
Validation that you should not use '*'
