### ISSUE TITLE
Federation fails when istio version is set to `latest`

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#1549]
**Describe the bug**
The following yaml in the `Mesh` can cause federation to fail:
```
      installation:
        cluster: cluster-0
        namespace: istio-system
        podLabels:
          istio: pilot
        region: us-east-1
        version: latest
```

Specifically `version: latest`

When building our `EnvoyFilter` we do the following check: https://github.com/solo-io/gloo-mesh/blob/a8b45d57a0faeb4d4218e148f0617c23ac123ea1/pkg/mesh-networking/translation/istio/mesh/federation/federation_translator.go#L224

We should have a default when this semver translation fails.

**To Reproduce**
Install istioctl using tag `latest`

**Expected behavior**
We choose a default behavior
