### ISSUE TITLE
Support for additional image registries

### ISSUE THREAD

**Issue by rvennam** [solo-io/gloo-mesh#1553]
1. Host gloo mesh images on a secondary registry, such as docker hub
2. Provide mechanism to specify `hub` as flags in meshctl and helm

**Comment by ashleywang1** [comment]
#2 is already doable by passing in the following helm values.yaml
```
discovery:
  image:
    registry: quay.io/solo-io
networking:
  image:
    registry: quay.io/solo-io
```
when installing gloo mesh OSS and the following agent-values.yaml
```
certAgent:
  image:
    registry: quay.io/solo-io
```
when registering an OSS cluster.
