### ISSUE TITLE
Istio Gateway AUTO_PASSTHROUGH breaks Mesh federation

### ISSUE THREAD

**Issue by harveyxia** [solo-io/gloo-mesh#1560]
**Describe the bug**
In 1.9.5 Istio changed their Gateway `AUTO_PASSTHROUGH` [implementation](https://github.com/istio/istio/blob/b3bdc0c71bfd6152e645b8a12074f560efa42882/pilot/pkg/networking/core/v1alpha3/gateway.go#L642) due to a [security vulnerability](https://istio.io/latest/news/security/istio-security-2021-006/). They no longer use an Envoy `sni_cluster` so our current approach of using an Envoy `tcp_cluster_rewrite` to modify the remote cluster name to the local cluster name on the server side no longer works.

The new Istio implementation instead looks at the hosts specified on the Gateway CR, and creates routing config (i.e. a filter chain) per known Service, but these filter chains match on the “DNSSrvSubsetKey” cluster name (e.g. “outbound_.9080_._.reviews.bookinfo.svc.cluster.local”), whereas our ServiceEntries representing remote services on the client side use the federated FQDN as the SNI (e.g. “reviews.bookinfo.svc.remote-cluster.soloio”).

**Workaround:**

Create ServiceEntries on the server side in order to produce mappings from the SNI that the client sends (which is qualified with the cluster name) to the correct destination. For example,

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: reviews-remote
  namespace: istio-system # must be in same namespace as gateway
spec:
  resolution: DNS
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 9080
    protocol: HTTP
  exportTo:
  - .
  hosts:
  - reviews.bookinfo.svc.remote-cluster.soloio
  endpoints:
  - address: reviews.bookinfo.svc.cluster.local
```

Additionally, a DestinationRule is needed to configure the ServiceEntry with ISTIO_MUTUAL tls so that this ServiceEntry shows up in the gateway Envoy config, since the new auto_passthrough implementation filters out any plaintext destinations. For example,

```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ratings-bookinfo-federated
  namespace: istio-system
spec:
  host: reviews.bookinfo.svc.remote-cluster.soloio
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

**Additional context**
Affects Istio versions >= 1.9.5 and >= 1.8.6
