### ISSUE TITLE
Add support for discovering `Service` `ExternalIP`

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo-mesh#1564]
Currently mesh ingress discovery only checks `LoadBalancer` `Status` or `NodePort` for an external address, however, some users are using `ExternalIPs`. Gloo Mesh should be able to discover those as well.

**Comment by ashleywang1** [comment]
Needs backport

**Comment by ashleywang1** [comment]
Backport was done here: https://github.com/solo-io/gloo-mesh-enterprise/pull/568

**Comment by ashleywang1** [comment]
Needs a Gloo Mesh Enterprise release

**Comment by ashleywang1** [comment]
Hi, this has been released and tested in Gloo Mesh v1.0.11.

The following service (in a kind cluster):
```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  externalIPs:
  - 80.11.12.10
...
  type: LoadBalancer
status:
  loadBalancer: {}
```

generates the following Mesh discovery object:
```
apiVersion: discovery.mesh.gloo.solo.io/v1
kind: Mesh
metadata:
  name: istiod-istio-system-mgmt-cluster
  namespace: gloo-mesh
spec:
  agentInfo:
    agentNamespace: gloo-mesh
  istio:
    ingressGateways:
    - externalAddress: 80.11.12.12
```
