### ISSUE TITLE
meshctl configuration file

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo-mesh#1584]
meshctl should be made to support a configuration file with default values. this is especially useful so that a user can predefine a mapping of clusters to kubeconfig entries like so:
```yaml
clusters:
  managementPlane: #reserved special name for the management cluster
    kubeConfig: /Users/ilackarms/.kube/config
    kubeContext: kind-mgmt-cluster
  remote-cluster: # data plane cluster
    kubeConfig: /Users/ilackarms/.kube/config
    kubeContext: kind-remote-cluster
  mgmt-cluster: # mgmt cluster is also registered as data plane
    kubeConfig: /Users/ilackarms/.kube/config
    kubeContext: kind-mgmt-cluster
```
We can store this file in the user's  home dir, e.g.`${HOME}/.meshctl/config.yaml` via a `meshctl configure` command (interactively configures meshctl like `aws configure`). We can then reference this file in subsequent `meshctl` commands which automate cluster interaction rather than requiring the user to always pass their kubeconfig/context for each cluster individually. it also makes it much easier to support commands that interact with multiple clusters at once.
