### ISSUE TITLE
Please consider adding PSPs for the bookinfo demo app

### ISSUE THREAD

**Issue by caleygoff-invitae** [solo-io/gloo-mesh#1632]
**Describe the requested changes**
I realize that PSPs are being deprecated, however for users who still use them in their environments and are restricted this app cannot run in those environments with out the proper PSPs created.

This deployment deploys fine but for clusters that have restricted PSPs that dont allow for capabilities on pods this will fail to launch. We deploy our workloads in EKS and remove the permissive PSP in our clusters restricting them.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-mesh/latest/guides/#bookinfo-deployment 

**Additional context**
I have included the PSP that was required for our cluster in order for the bookinfo apps to turn on

```
# Pod security policies will be created for service account 'bookinfo-details' in namespace 'bookinfo' with following workdloads:
#	Kind: Deployment, Name: details-v1, Image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  creationTimestamp: null
  name: psp-for-bookinfo-bookinfo-details
spec:
  allowedCapabilities:
    - NET_ADMIN
    - NET_RAW
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - max: 0
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - emptyDir
    - configMap
    - projected
    - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: use-psp-by-bookinfo:bookinfo-details
  namespace: bookinfo
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-for-bookinfo-bookinfo-details
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: use-psp-by-bookinfo:bookinfo-details-binding
  namespace: bookinfo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-psp-by-bookinfo:bookinfo-details
subjects:
  - kind: ServiceAccount
    name: bookinfo-details
    namespace: bookinfo
---
# Pod security policies will be created for service account 'bookinfo-productpage' in namespace 'bookinfo' with following workdloads:
#	Kind: Deployment, Name: productpage-v1, Image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  creationTimestamp: null
  name: psp-for-bookinfo-bookinfo-productpage
spec:
  allowedCapabilities:
    - NET_ADMIN
    - NET_RAW
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - max: 0
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - emptyDir
    - configMap
    - projected
    - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: use-psp-by-bookinfo:bookinfo-productpage
  namespace: bookinfo
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-for-bookinfo-bookinfo-productpage
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: use-psp-by-bookinfo:bookinfo-productpage-binding
  namespace: bookinfo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-psp-by-bookinfo:bookinfo-productpage
subjects:
  - kind: ServiceAccount
    name: bookinfo-productpage
    namespace: bookinfo
---
# Pod security policies will be created for service account 'bookinfo-ratings' in namespace 'bookinfo' with following workdloads:
#	Kind: Deployment, Name: ratings-v1, Image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  creationTimestamp: null
  name: psp-for-bookinfo-bookinfo-ratings
spec:
  allowedCapabilities:
    - NET_ADMIN
    - NET_RAW
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - max: 0
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - emptyDir
    - configMap
    - projected
    - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: use-psp-by-bookinfo:bookinfo-ratings
  namespace: bookinfo
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-for-bookinfo-bookinfo-ratings
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: use-psp-by-bookinfo:bookinfo-ratings-binding
  namespace: bookinfo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-psp-by-bookinfo:bookinfo-ratings
subjects:
  - kind: ServiceAccount
    name: bookinfo-ratings
    namespace: bookinfo
---
# Pod security policies will be created for service account 'bookinfo-reviews' in namespace 'bookinfo' with following workdloads:
#	Kind: Deployment, Name: reviews-v1, Image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
#	Kind: Deployment, Name: reviews-v2, Image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  creationTimestamp: null
  name: psp-for-bookinfo-bookinfo-reviews
spec:
  allowedCapabilities:
    - NET_ADMIN
    - NET_RAW
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - max: 0
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - emptyDir
    - configMap
    - projected
    - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: use-psp-by-bookinfo:bookinfo-reviews
  namespace: bookinfo
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-for-bookinfo-bookinfo-reviews
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: use-psp-by-bookinfo:bookinfo-reviews-binding
  namespace: bookinfo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-psp-by-bookinfo:bookinfo-reviews
subjects:
  - kind: ServiceAccount
    name: bookinfo-reviews
    namespace: bookinfo
---
```
