### ISSUE TITLE
Missing PSP for petstore app 

### ISSUE THREAD

**Issue by caleygoff-invitae** [solo-io/gloo-mesh#1634]
**Describe the requested changes**
Similar to issue https://github.com/solo-io/gloo-mesh/issues/1632 this is for the [petstore](https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml) app linked on the below page. I put the app in the petstore namespace. However our restricted environment still required a PSP to get the workload to run. I additionally added a service account for association  of the PSP via the RBAC.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-mesh/latest/guides/traffic_policy/

**Additional context**
```
# Pod security policies will be created for service account 'petstore' in namespace 'petstore' with following workdloads:
#	Kind: Deployment, Name: petstore, Image: soloio/petstore-example:latest
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  creationTimestamp: null
  name: psp-for-petstore-petstore
spec:
  allowedCapabilities:
    - NET_ADMIN
    - NET_RAW
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - max: 0
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - secret
    - emptyDir
    - configMap
    - projected
    - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: use-psp-by-petstore:petstore
  namespace: petstore
rules:
  - apiGroups:
      - policy
    resourceNames:
      - psp-for-petstore-petstore
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: use-psp-by-petstore:petstore-binding
  namespace: petstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-psp-by-petstore:petstore
subjects:
  - kind: ServiceAccount
    name: petstore
    namespace: petstore
---

##########################
#                        #
#        Example         #
#        Service         #
#                        #
#                        #
##########################
# petstore service
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petstore
  name: petstore
  namespace: petstore
spec:
  selector:
    matchLabels:
      app: petstore
  replicas: 1
  template:
    metadata:
      labels:
        app: petstore
    spec:
      serviceAccountName: petstore
      containers:
        - image: soloio/petstore-example:latest
          name: petstore
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: petstore
  labels:
    service: petstore
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: petstore
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: petstore
  labels:
    service: petstore
```
