### ISSUE TITLE
TrafficPolicies Should Expose configuration for TCP Settings

### ISSUE THREAD

**Issue by davidmortiz** [solo-io/gloo-mesh#1835]
We currently run two Gloo Mesh enabled Istio Clusters and occasionally we run into AWS NLB timeout issues when making cross-cluster gRPC service calls related to this issue

https://medium.com/tenable-techblog/lessons-from-aws-nlb-timeouts-5028a8f65dda

We define a traffic policy at the mesh level for our service

```
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  name: some-api
  namespace: gloo-mesh

spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
      - clusterName: cluster-1
        name: some-api
        namespace: some-namespace
  policy:
    requestTimeout: 1s
    retries:
      attempts: 3
      perTryTimeout: 1s
```

We've noticed that even with retries, we occasionally run into issues where gRPC calls fail from clients running in a different cluster.  We have resolved this by putting a destination rule in the client's namespace that specifies TCP keep-alive settings that keep the NLB connections from getting closed out from underneath us.

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
  name: some-api
  namespace: client-namespace
spec:
  exportTo:
  - .
  host: some-api.global
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 500ms
        maxConnections: 100
        tcpKeepalive:
          interval: 1m
          time: 4m
    tls:
      mode: ISTIO_MUTUAL
```

It would be great if we could specify TCP connection policies at the mesh level via Traffic Policies so that we can ensure we don't run into issues when making gRPC calls between clusters and so that we don't have to override destination rules manually.
