### ISSUE TITLE
Support VirtualDestination as a destinationSelector in TrafficPolicy

### ISSUE THREAD

**Issue by nmnellis** [solo-io/gloo-mesh#1898]
**Is your feature request related to a problem? Please describe.**
If i create a virtualDestination with a global hostname (reviews.global). i want to be able to add policies to that hostname such as retries and timeouts.

**Describe the solution you'd like**

1s timeout on http-backend.solo.io

```yaml
apiVersion: networking.mesh.gloo.solo.io/v1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: gloo-mesh
spec:
  federation:
    selectors:
      - { }
  meshes:
    - name: istiod-istio-system-cluster-0
      namespace: gloo-mesh
    - name: istiod-istio-system-cluster-1
      namespace: gloo-mesh
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualDestination
metadata:
  name: backend
  namespace: gloo-mesh
spec:
  hostname: http-backend.solo.io
  port:
    number: 8090
    protocol: http
    targetNumber: 8090
    destinationSelectors:
      - kubeServiceMatcher:
          labels:
            app: backend
  virtualMesh:
    name: virtual-mesh
    namespace: gloo-mesh
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: frontend-timeout
spec:
  destinationSelector:
  - virtualDestinations:
      name: myvirtualdestination
      namespace: gloo-mesh
  policy:
    requestTimeout: 1s
```
