### ISSUE TITLE
EnvoyFilter applied to BOOTSTRAP causes errors in agent

### ISSUE THREAD

**Issue by dobriensq** [solo-io/gloo-mesh#1935]
### Gloo Mesh Version

1.2.x (latest stable)

### Istio Version

1.12.x

### Describe the bug

I'm testing an `EnvoyFilter` for an egress gateway to enable envoy's overload manager. When this resource exists, I get the following error in the gloo mesh agent, which seems to prevent the propagation of other gloo resources.

```
{"level":"error","ts":1643756339.068289,"msg":"pkg/mod/k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167: Failed to watch *v1alpha3.EnvoyFilter: failed to list *v1alpha3.EnvoyFilter: v1alpha3.EnvoyFilterList.Items: []v1alpha3.EnvoyFilter: v1alpha3.EnvoyFilter.v1alph
a3.EnvoyFilter.Spec: unmarshalerDecoder: unknown value \"BOOTSTRAP\" for enum istio.networking.v1alpha3.EnvoyFilter_ApplyTo, error found in #10 byte of ...|ateway\"}}}},{\"apiVer|..., bigger context ...|ctor\":{\"labels\":{\"istio\":\"weaver-egressgateway\"}}}},{\"apiVe
rsion\":\"networking.istio.io/v1alpha3\",\"ki|...\n","stacktrace":"k8s.io/klog/v2.(*loggingT).printDepth\n\t/go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:732\nk8s.io/klog/v2.ErrorDepth\n\t/go/pkg/mod/k8s.io/klog/v2@v2.5.0/klog.go:1456\nk8s.io/apimachinery/pkg/util/runtime.l
ogError\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:114\nk8s.io/apimachinery/pkg/util/runtime.HandleError\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/runtime/runtime.go:108\nk8s.io/client-go/tools/cache.DefaultWatchErrorHandler\n\t/go/
pkg/mod/k8s.io/client-go@v0.20.5/tools/cache/reflector.go:138\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\t/go/pkg/mod/k8s.io/client-go@v0.20.5/tools/cache/reflector.go:222\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachine
ry@v0.20.5/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:156\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\t/go/pkg/mod/k8s.io/client-go@v0.20.5/tools/cache/reflector.go:220\
nk8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:56\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:73"}
```

This is the envoy filter in question:
 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: egress-overload-manager
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: egressgateway
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
        overload_manager:
          actions:
          - name: envoy.overload_actions.shrink_heap
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.7
          - name: envoy.overload_actions.stop_accepting_requests
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.85
          - name: envoy.overload_actions.stop_accepting_requests
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.9
          - name: envoy.overload_actions.stop_accepting_connections
            triggers:
            - name: envoy.resource_monitors.fixed_heap
              threshold:
                value: 0.9
          refresh_interval: 1s
          resource_monitors:
          - name: envoy.resource_monitors.fixed_heap
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
              max_heap_size_bytes: 1073741824.0
```

### Steps to reproduce the bug

1. `kubectl apply` the above config
2. Look at the gloo agent logs

### Expected Behavior

I expected the gloo agent to be able to successfully watch the envoy filter.

### Additional Context

```
$ istioctl version
client version: 1.11.4
control plane version: 1.12.2
data plane version: 1.11.3 (3 proxies), 1.12.2 (73 proxies), 1.11.4 (62 proxies)
$ kubectl version --short
Client Version: v1.22.4
Server Version: v1.20.11-eks-f17b81
```
