### ISSUE TITLE
externalAddress is not populated for MeshSpec.Istio.IngressGatewayInfo

### ISSUE THREAD

**Issue by m0ps** [solo-io/gloo-mesh#993]
We are trying to evaluate service-mesh-hub with private GKE clusters and istio 1.6, but we faced with the following issue:

MeshSpec.Istio.IngressGatewayInfo doesn't contain **externalAddress**, so generation of ServiceEntries fails with:
```
2020-10-06T13:28:14.256Z        ERROR   networking.reconcile-15 failed upserting resource       {"resource": "sleep.foo.svc.cluster-1.global.istio-system.cluster-2.*v1alpha3.ServiceEntry", "err": "admission webhook \"validation.istio.io\" denied the request: configuration is invalid: endpoint address \"\" is not a valid FQDN or an IP address"}
```

Spec snippet:
```
spec:
  agentInfo:
    agentNamespace: service-mesh-hub
  istio:
    citadelInfo:
      citadelServiceAccount: istiod-service-account
      trustDomain: cluster.local
    ingressGateways:
    - externalTlsPort: 32001
      tlsContainerPort: 15443
      workloadLabels:
        istio: ingressgateway
    installation:
      cluster: cluster-1
      namespace: istio-system
      podLabels:
        istio: pilot
      version: 1.6.8
status:
  appliedVirtualMesh:
    observedGeneration: "4"
    ref:
      name: virtual-mesh
      namespace: service-mesh-hub
    spec:
      federation: {}
      meshes:
      - name: istiod-istio-system-cluster-1
        namespace: service-mesh-hub
      - name: istiod-istio-system-cluster-2
        namespace: service-mesh-hub
      mtlsConfig:
        autoRestartPods: true
        shared:
          rootCertificateAuthority:
            generated:
              orgName: service-mesh-hub
              rsaKeySizeBytes: 4096
              ttlDays: 356
  observedGeneration: "1"
```
Service spec:
```
spec:
  clusterIP: 172.16.5.134
  externalTrafficPolicy: Cluster
  ports:
  - name: http2
    nodePort: 32381
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31538
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tls
    nodePort: 32001
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort
```

Istio version 1.6.8
service-mesh-hub - 0.8.1

The same config (not exactly the same due to the API changes, but similar) works fine with 0.6.1.

Any suggestion will be very helpful, cuz there is a lack of any useful information on a web.
